import { VOTER_REGISTRATION_ADDRESS, VOTER_REGISTRATION_ABI } from "./voterRegistrationConfig"
import { CANDIDATE_REGISTRY_ADDRESS, CANDIDATE_REGISTRY_ABI } from "./candidateRegistryConfig"

export {
  VOTER_REGISTRATION_ADDRESS as CONTRACT_ADDRESS,
  VOTER_REGISTRATION_ABI as CONTRACT_ABI,
  CANDIDATE_REGISTRY_ADDRESS,
  CANDIDATE_REGISTRY_ABI,
}

